m2scorer: ../m2scorer/m2scorer/m2scorer
fm:
   false_bpe_src: ../data/bfit/eval/bfit-16000-rev/false.fm.src
   false_bpe_trg: ../data/bfit/eval/bfit-16000-rev/false.fm.trg
   valid_bpe_src: ../data/bfit/eval/bfit-16000-rev/valid.fm.src
   valid_bpe_trg: ../data/bfit/eval/bfit-16000-rev/valid.fm.trg
   test_bpe_src: ../data/bfit/eval/bfit-16000-rev/test.fm.src
   test_bpe_trg: ../data/bfit/eval/bfit-16000-rev/test.fm.trg
   valid_m2: ../corpora/falko-merlin/data/fm-dev.m2
   test_m2: ../corpora/falko-merlin/data/fm-test.m2
wf:
   false_bpe_src: ../data/bfit/eval/bfit-16000-rev/false.wf.src
   false_bpe_trg: ../data/bfit/eval/bfit-16000-rev/false.wf.trg
   valid_bpe_src: ../data/bfit/eval/bfit-16000-rev/valid.wf.src
   valid_bpe_trg: ../data/bfit/eval/bfit-16000-rev/valid.wf.trg
   test_bpe_src: ../data/bfit/eval/bfit-16000-rev/test.wf.src
   test_bpe_trg: ../data/bfit/eval/bfit-16000-rev/test.wf.trg
   valid_m2: ../corpora/conll13/release2.3.1/original/data/official-preprocessed.m2
   test_m2: ../corpora/conll14/conll14st-test-data/noalt/official-2014.combined.m2

