m2scorer: ../m2scorer/m2scorer/m2scorer
fm:
   false_bpe_src: ../data/fmmt/eval/fmmt-16000-rev/false.src
   false_bpe_trg: ../data/fmmt/eval/fmmt-16000-rev/false.trg
   valid_bpe_src: ../data/fmmt/eval/fmmt-16000-rev/valid.src
   valid_bpe_trg: ../data/fmmt/eval/fmmt-16000-rev/valid.trg
   test_bpe_src: ../data/fmmt/eval/fmmt-16000-rev/test.src
   test_bpe_trg: ../data/fmmt/eval/fmmt-16000-rev/test.trg
   valid_m2: ../corpora/falko-merlin/data/fm-dev.m2
   test_m2: ../corpora/falko-merlin/data/fm-test.m2

